### ISSUE TITLE
Cloudfront rate-limiting not handled

### ISSUE THREAD

**Issue by RonitRay** [mehulcse/findmyslot#3]
Cowin APIs are behind a CloudFront CDN that after a certain number/frequency of requests blocks the device for some time. I'm not sure how long since it only happened to me once, but it is likely around half an hour without any requests.

When this limit is exceeded, all GET requests to the API return a 403 Forbidden error

403 Forbidden error is not handled by your client. There is no message or alert that a block has been imposed for a while and the user should try again in a while. To the user it seems like the site is running as expected and refreshing at the defined frequency. It's possible that if they keep the tab open the rate limit will persist.

**Comment by jjmanglani01** [comment]
This is an error from open APIs which we are using to fetch data.
We are currently using useQuery which is taking care of retry logic for API.
Although we will add try...catch block to avoid error

If this happens again let us know.
Thanks for pointing that out.

**Comment by jjmanglani01** [comment]
Hi,
This issue is fixed in this commit https://github.com/mehulcse/findmyslot/commit/42cb4353cf2a2458986c8cc7ee7287254bc3c309
