### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Rushabh5000** [mehulcse/findmyslot#7]
NOT AN ISSUE

Hey, I'm facing the 403 Forbidden issue while trying to call it from GCP. It seems locations out of India are not allowed to access these API's. How did you manage to host?

![Screenshot (108)](https://user-images.githubusercontent.com/16048580/117539570-ead5e980-b028-11eb-9fc6-7c7e1c24dac0.png)

**Comment by mehulcse** [comment]
We're consuming the Co-Win APIs so even on our platform it may not be accessible outside India. You can write a proxy service and host it in India. That is something you can consume on Front-end. IF that works.

**Comment by Rushabh5000** [comment]
Alright. Thanks
